// <auto-generated />
namespace Veil.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CartItem_IsNew_InPK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartItem_IsNew_InPK));
        
        string IMigrationMetadata.Id
        {
            get { return "201511141428243_CartItem_IsNew_InPK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
