// <auto-generated />
namespace Veil.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Setup_Event_Id_AddBackCascadeDelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Setup_Event_Id_AddBackCascadeDelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201511090138429_Setup_Event_Id_AddBackCascadeDelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
